### PR TITLE
Fix links to atom jobs in the atom state renderers

### PR DESCRIPTION
**Pull request by 0xced**
Without using the UrlHelper, the link to _Atom details_ could be wrong and lead to HTTP 404 errors.

For example, it would point to http://localhost:5000/jobs/atoms/10119 instead of http://localhost:5000/hangfire/jobs/atoms/10119 when using the default `app.UseHangfireDashboard()` method that maps the Hangfire dashboard on `/hangfire`.

### CODE REVIEW

**Comment by ahydrax** [comment]
Hi there, thanks for contribution!
Is there a safer way to extract razor page and get url? I worrying about using a reflection

**Comment by 0xced** [comment]
I just found way, without using reflection, to get the `UrlHelper`: af17f6f556ade2569e222eae5638560b8d804dbe

It should be much safer!

**Comment by ahydrax** [comment]
Wow! Looks good to me, let me test it before pushing to live.

**Review by ahydrax — APPROVED** [review]

**Comment by 0xced** [comment]
Thanks for merging. And I see that version 0.4.4 is already released, awesome! 🥳

**Comment by 0xced** [comment]
For the record: the `RazorPage` will be exposed as a public property on `HtmlHelper` in the next version of Hangfire: https://github.com/HangfireIO/Hangfire/commit/1ae167e3ffc87429a64cf95201c40508101cf25c

I'll open a new pull request to simplify the current implementation.

**Pull request merged**
